language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
sudo: required
install:
  - sudo apt-get install python-pandas
  - pip install .
  - pip install -r requirements.txt
  - pip install  xlwt
# command to run tests
script: nosetests