sudo: required
language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo apt-get install python-pandas; fi
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
script:
  - pytest --cov=opentargets --cov-report term tests/ --fulltrace
notifications:
  email:
    recipients:
    - ops@opentargets.org
    on_success: never
    on_failure: always
after_success:
  - codecov
deploy:
  provider: pypi
  user: "${PYPI_USERNAME}"
  password: "${PYPI_PASSWORD}"
   on:
    tags: true